name = "simc-editor"
compatibility_date = "2023-10-30"

[site]
bucket = "./build"

[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "20"

[env.production]
routes = [
  { pattern = "/*", script = "index.html" }
]